#!/bin/bash

###
# Script to compute CpG coverage 
# Input is the '.CpG' output file generated by Misha's script novo5mc.jar 
###

less $1|awk '{if(NR%2==1){sum=$4+$5;print $1"\t"$2"\t"$3"\t"sum}}' > $1.TCsum.plus
less $1.TCsum.plus |awk '{print NR"\t"$0}' >  $1.TCsum.plus.n
less $1|awk '{if(NR%2!=1){sum=$4+$5;print $1"\t"$2"\t"$3"\t"sum}}' > $1.TCsum.minus
less $1.TCsum.minus  |awk '{print NR"\t"$0}' >  $1.TCsum.minus.n
join -1 1 -2 1 $1.TCsum.plus.n $1.TCsum.minus.n |awk '{mean=($5+$9)/2;print $1"\t"mean}' > $1.avCov
rm $1.TCsum.plus
rm $1.TCsum.plus.n
rm $1.TCsum.minus
rm $1.TCsum.minus.n
