#!/usr/bin/perl

#### Computing an estimate of the global bisulfite conversion rate for human and lambda #####
# based on the files generated by TABSQC in /projects/tab/QCreports/libID/lane/lane_bsConvert.tbl 
# Input = path to one bsConvert.tbl file
# Output = file with lambda and human BS conversion rates
# Note (for final repor): tfor each library
# in case there are several lanes, the minimal bs conversion rate is given
# QC check whether the bs conv rates of all lanes of same lib are roughly the same
# Method:
# For lambda and human, use the tag column and the minimum value of the range 
# for example if range (percent converted) is 20-30, use 20
# Multiply all those percents converted by the number of tags
# Sum thoses numbers and divide by the total number of tags (all ranges)

$file=$ARGV[0];

if(-e $file) {
	print "File $file is being processed\n";
}
if(!open(FIC,$file)) {
	print "Sorry it is not possible to open the file $file\n"; exit;
}

use File::Basename;
($name,$dir,$suffix)=fileparse($file);
($v,$p,$tab,$QC,$lib)=split(/\//,$dir);
($flowcell,$lane,$bsConv)=split(/_/, $name);

# Output file name
open(OUT, ">>bisulfiteConvRates_${lib}_${flowcell}_${lane}.txt");

$n1=0;
$t1=0;

while(defined($l=<FIC>)) {
	#print "line $.\n";
	if($.>5 && $.<17) {
		($range,$tag,$type)=split(/\t/,$l);
		($min,$max)=split(/-/,$range);
		$n=($min*$tag)+$n1;
		$t=$tag+$t1;
		$n1=$n;
		$t1=$t;
	}
	if ($.>16 && $l=~m/ref/) {
		# lambda data end
		$convl=$n/$t;
		print(OUT "Lambda_BS_Convertion_Rate\t$convl\n");
		print(OUT "Total_number_of_Lambda_tags\t$t\n");
		$n1=0;
		$t1=0;
	}
	if($.>19) {
		($range,$tag,$type)=split(/\t/,$l);
		($min,$max)=split(/-/,$range);
		$n=($min*$tag)+$n1;
		$t=$tag+$t1;
		$n1=$n;
		$t1=$t;	
	}
}
$convh=$n/$t;
print(OUT "Human_BS_Conversion_Rate\t$convh\n");
close OUT;
close FIC;
